12 implement twilio sms
Machinata/hestia pull request #37
Opened 2024-12-31 05:07 UTC by BenjaminPalko

2025-01-01 02:50 UTC, DanMihailescu commented on .env
> +DATABASE_URL="postgres://hestia:test123@localhost:5432/hestia"
where that empty line at the end

2025-01-01 03:46 UTC, piopi requested changes

2025-01-01 03:46 UTC, piopi commented on .env
> +TWILIO_PHONE_NUMBER=
Prefill them please with CHANGE_ME

2025-01-01 03:46 UTC, piopi commented on src/lib/server/twilio/twilio.config.ts
> +	}
Add a script instead + add it to `bun dev`

2025-01-02 19:02 UTC, piopi approved these changes

2025-01-02 19:02 UTC, piopi commented on scripts/validate-env.ts
Very nice!

2025-01-03 01:11 UTC, merged